Css fixes
YungTatyu/Jin pull request #70
Opened 2024-10-03 12:31 UTC by deerman31

1. tozeki さんによる CSS の修正を適用
2. addNewTransaction の 4 つの入力フィールドにバリデーション処理を追加
3. 各リストの表示高さを調整
4. 入力されたSOLをスマートコントラクトに渡すためにlamportsの単位に変換するようにしました。

これらの変更により、UIの改善とデータ入力の信頼性向上を図りました。

2024-10-03 13:48 UTC, tozeki722105 submitted a review, later dismissed
主にCSSの修正箇所を確認しました
format修正していただき、ありがとうございます

2024-10-03 13:58 UTC, rikeda-cloud requested changes
より細かなバグは自分がテストする際に見ようかなと思います。
2箇所バリデーションについてコメントしたので確認お願いします。

2024-10-03 13:58 UTC, rikeda-cloud commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  }
判定条件が逆？

2024-10-03 13:58 UTC, rikeda-cloud commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  return !isNaN(num) && isFinite(num);
"00"を許容

2024-10-03 14:00 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  }
ほんまや、初歩的なミスでした。

2024-10-03 15:09 UTC, YungTatyu reviewed
対応ありがとうございます！

2024-10-03 15:09 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +function validateAddNewTransaction(
この関数名だと、trueかfalseかどちらが正しいinputなのか確証が持てないです。
以下のような命名はどうでしょうか
```ts
isTransactionValid()
isTxInfoValid()
```

2024-10-03 15:09 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
>        Number(refundDeadline) * 24 * 60 * 60,
jsでNumber型は浮動小数点数みたいなので、値が非常に大きい場合、
精度の問題がありそうです。
少なくとも以下は、浮動小数点の計算になってしまっていると思います。
BigNumber型ではだめですか？
```ts
      Number(refundDeadline) * 24 * 60 * 60,
```

2024-10-03 15:09 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/Home/Body/Buyer/UnrecoverableList.tsx
> +  };
こちらも浮動小数点になってしまっています。
特にお金の計算に使っている場合は、注意が必要です。

2024-10-03 20:27 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +function validateAddNewTransaction(
validateAddNewTransaction()で一気にvalidationせずに各入力値を変換する際に一緒にvalidationするように変更しました。

2024-10-03 20:27 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
>        Number(refundDeadline) * 24 * 60 * 60,
amountの部分の型に関しては全てBigNumberに変更しました。

2024-10-04 01:24 UTC, YungTatyu reviewed
昨日reviewしたバリデーションの箇所の変更が反映されていないですか？

2024-10-04 02:18 UTC, YungTatyu reviewed
気になった点をコメントしました。

2024-10-04 02:18 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  const roundedDays = dayNumber.integerValue(BigNumber.ROUND_DOWN);
この時点で小数点以下を考慮する必要があるんですか？
これの上でinputの範囲を確認しているように見えます。

2024-10-04 02:18 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +    const num_of_transactions = await countTransactions(
num_of_transactionsだけsnakecaseになっています。

2024-10-04 02:18 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (transactionInfo.length === 0 || transactionInfo.length > 50) {
`transactionInfo.length > 50`
lengthの値が50になっていますが、100ではなかったでしたっけ？
定数が定義されていたと思うので、それを使ってマジックナンバーを避けた方がいいと思います。

2024-10-04 02:21 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +    const num_of_transactions = await countTransactions(
修正します

2024-10-04 02:23 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  const roundedDays = dayNumber.integerValue(BigNumber.ROUND_DOWN);
冗長なようなので削除しておきます。

2024-10-04 02:24 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (transactionInfo.length === 0 || transactionInfo.length > 50) {
ここは大まかな値を置いただけですが、
その定数がどこで定義されているのかわからないので、自分で定義しちゃいますね

2024-10-04 02:25 UTC, rikeda-cloud commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (transactionInfo.length === 0 || transactionInfo.length > 50) {
ちなみに、スマートコンストラクタ側での受け入れは文字数ではなく、byte数なので、
3bytesの文字('あ')を34文字入力すると、フロントエンドでは成功するが、バックエンドでは失敗するような挙動があります

2024-10-04 02:30 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (transactionInfo.length === 0 || transactionInfo.length > 50) {
> ちなみに、スマートコンストラクタ側での受け入れは文字数ではなく、byte数なので、 3bytesの文字('あ')を34文字入力すると、フロントエンドでは成功するが、バックエンドでは失敗するような挙動があります

半角英数字のみに絞っちゃいますかね。

2024-10-04 02:37 UTC, YungTatyu commented
僕の環境の問題なのか分からないのですが、frontの見た目がおかしく見えます。
JinやPlease connect your wallet to access buyer features.のような文字が白色になっていて、文字が全然みえないです。

2024-10-04 02:40 UTC, rikeda-cloud commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (transactionInfo.length === 0 || transactionInfo.length > 50) {
良いと思います

2024-10-04 02:41 UTC, rikeda-cloud commented
> 僕の環境の問題なのか分からないのですが、frontの見た目がおかしく見えます。 JinやPlease connect your wallet to access buyer features.のような文字が白色になっていて、文字が全然みえないです。

自分の環境では文字の色は黒色です。
校舎Macで作業していたときにkusanoさんも同じ現象が起きていたと思います

2024-10-04 02:43 UTC, rikeda-cloud commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +    const num_of_transactions = await countTransactions(
多分、少し前に自分が記述した箇所だったと思います。
すみません。

2024-10-04 05:39 UTC, rikeda-cloud approved these changes, later dismissed
私が指摘した部分のすべての修正を確認しました。
修正ありがとうございました！
LGTM!

2024-10-04 05:39 UTC, rikeda-cloud commented on srcs/app/frontend/src/app/components/api.ts
> +    const { blockhash } = await CONNECTION.getRecentBlockhash();
getLatestBlockhashが正しいです。
恐らく、mainブランチのコンフリクト解消時に戻してしまったと思われます。
```
const { blockhash } = await CONNECTION.getLatestBlockhash();
```

2024-10-04 05:43 UTC, deerman31 commented on srcs/app/frontend/src/app/components/api.ts
> +    const { blockhash } = await CONNECTION.getRecentBlockhash();
すでに修正し、pushしているのでそちらの差分は間違いだと思います。
現在修正したブランチのvscodeの画像です。

<img width="1440" alt="スクリーンショット 2024-10-04 14 42 50" src="https://github.com/user-attachments/assets/f4abb3a6-7338-48da-9d41-f5103600d0d6">

const { blockhash } = await CONNECTION.getLatestBlockhash();

2024-10-04 05:49 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (!/^[a-zA-Z0-9]+$/.test(transactionInfo)) {
これは半角の記号も許容していますか？
これらは許容してあげたいです。
例えば
`;`,`:`, `,`
理由としては、サービス提供者側で、データの区切りで使うか可能性が高いからです。
例
```
netflix, standard plan, price, customer name
```

2024-10-04 05:49 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +      error: 'Transaction info should be no longer than 100 characters',
error: 'Transaction info should be no longer than 100 characters',
ここの文字数に定数を使うといいと思います。
以下のような感じでできると思います。
```ts
error: `Transaction info should be no longer than ${MAX_TRANSACTION_INFO} characters`
```

2024-10-04 05:54 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (!/^[a-zA-Z0-9]+$/.test(transactionInfo)) {
,だけ許容するように修正します。

2024-10-04 05:55 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +      error: 'Transaction info should be no longer than 100 characters',
修正します。

2024-10-04 05:57 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (!/^[a-zA-Z0-9]+$/.test(transactionInfo)) {
sellerが自由に定義できるフィールドなので、他の半角記号や空白も許容してあげたいです。
半角のptintableなら許容したいです。

2024-10-04 06:00 UTC, deerman31 commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (!/^[a-zA-Z0-9]+$/.test(transactionInfo)) {
> sellerが自由に定義できるフィールドなので、他の半角記号や空白も許容してあげたいです。 半角のptintableなら許容したいです。

半角英数と記号を全て許容するようにしました。

2024-10-04 06:31 UTC, rikeda-cloud approved these changes

2024-10-04 06:53 UTC, YungTatyu approved these changes

2024-10-04 06:53 UTC, YungTatyu commented on srcs/app/frontend/src/app/components/AddNewTransaction/AddNewTransactionComponent.tsx
> +  if (!/^[\x20-\x7E]+$/.test(transactionInfo)) {
これだけだと何を意味しているかわからないので、コメントがあるべきだとおもいます。

2024-10-04 07:03 UTC, tozeki722105 approved these changes

2024-10-04 09:09 UTC, merged